/*
 * Lukas Krampitz
 * Oct 8, 2020
 * 
 */
package guiexercise3;

/**
 *
 * @author Tacitor
 */
public class SlotMachine extends javax.swing.JFrame {

    //Machine vars
    static int wheel1;
    static int wheel2;
    static int wheel3;
    static int winNum;
    static int tokens = 100;

    /**
     * Creates new form SlotMachine
     */
    public SlotMachine() {
        initComponents();
        //set the title
        this.setTitle("Slot Machine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yellowPnl = new javax.swing.JPanel();
        greenPnl = new javax.swing.JPanel();
        gamePnl = new javax.swing.JPanel();
        wheel1lbl = new javax.swing.JLabel();
        wheel2lbl = new javax.swing.JLabel();
        wheel3lbl = new javax.swing.JLabel();
        spinBtn = new javax.swing.JButton();
        winLbl = new javax.swing.JLabel();
        tokenLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yellowPnl.setBackground(new java.awt.Color(255, 255, 0));

        greenPnl.setBackground(new java.awt.Color(36, 171, 21));
        greenPnl.setToolTipText("");
        greenPnl.setAutoscrolls(true);

        gamePnl.setBackground(new java.awt.Color(165, 232, 158));

        wheel1lbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        wheel1lbl.setText("0");

        wheel2lbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        wheel2lbl.setText("0");

        wheel3lbl.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        wheel3lbl.setText("0");

        spinBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        spinBtn.setText("Spin!");
        spinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinBtnActionPerformed(evt);
            }
        });

        winLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        winLbl.setText("Win 0");

        tokenLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tokenLbl.setText("Tokens: 100");

        javax.swing.GroupLayout gamePnlLayout = new javax.swing.GroupLayout(gamePnl);
        gamePnl.setLayout(gamePnlLayout);
        gamePnlLayout.setHorizontalGroup(
            gamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(wheel1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(wheel2lbl)
                .addGap(83, 83, 83)
                .addComponent(wheel3lbl)
                .addGap(70, 70, 70))
            .addGroup(gamePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(gamePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tokenLbl)
                .addGap(30, 30, 30))
        );
        gamePnlLayout.setVerticalGroup(
            gamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(gamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheel1lbl)
                    .addComponent(wheel2lbl)
                    .addComponent(wheel3lbl))
                .addGap(29, 29, 29)
                .addComponent(spinBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(gamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winLbl)
                    .addComponent(tokenLbl))
                .addContainerGap())
        );

        javax.swing.GroupLayout greenPnlLayout = new javax.swing.GroupLayout(greenPnl);
        greenPnl.setLayout(greenPnlLayout);
        greenPnlLayout.setHorizontalGroup(
            greenPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        greenPnlLayout.setVerticalGroup(
            greenPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout yellowPnlLayout = new javax.swing.GroupLayout(yellowPnl);
        yellowPnl.setLayout(yellowPnlLayout);
        yellowPnlLayout.setHorizontalGroup(
            yellowPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowPnlLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(greenPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        yellowPnlLayout.setVerticalGroup(
            yellowPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yellowPnlLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(greenPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yellowPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yellowPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinBtnActionPerformed
        // TODO add your handling code here:
        //consume 2 tokens and update display
        tokens -= 2;
        tokenLbl.setText("Tokens: " + tokens);

        //radomize the wheels
        wheel1 = (int) (Math.random() * 3) + 1;
        wheel2 = (int) (Math.random() * 3) + 1;
        wheel3 = (int) (Math.random() * 3) + 1;

        //update labels
        wheel1lbl.setText("" + wheel1);
        wheel2lbl.setText("" + wheel2);
        wheel3lbl.setText("" + wheel3);

        //check for a win
        if (wheel1 == wheel2 && wheel1 == wheel3) {
            //check for the differnt types of win
            if (wheel1 == 1) {
                winNum = 4;
            } else if (wheel1 == 2) {
                winNum = 8;
            } else if (wheel1 == 3) {
                winNum = 12;
            } else {
                System.out.println("No idea how you got here, but this is definatly a bug.");
            }
            
            //update win lablel and token count
            tokens += winNum;
            tokenLbl.setText("Tokens: " + tokens);
            winLbl.setText("Win " + winNum + "!");
            
        } else {
            
            //change the win lable to 0
            winLbl.setText("Win 0");
            
            //check if the player is out of coins
            if(tokens <= 0) {
                spinBtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_spinBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gamePnl;
    private javax.swing.JPanel greenPnl;
    private javax.swing.JButton spinBtn;
    private javax.swing.JLabel tokenLbl;
    private javax.swing.JLabel wheel1lbl;
    private javax.swing.JLabel wheel2lbl;
    private javax.swing.JLabel wheel3lbl;
    private javax.swing.JLabel winLbl;
    private javax.swing.JPanel yellowPnl;
    // End of variables declaration//GEN-END:variables
}
