package guiexercise1;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/*
 * Lukas Krampiz
 * Oct 8, 2020
 * 
 */
/**
 *
 * @author lukra1175
 */
public class MadLibs extends javax.swing.JFrame {
    

    static int randInt;
    static String madLib;
    static int verbPos;
    static int nounPos;
    static final int FILE_FIELD_NUM = 10;
    static String[] sentencesArr = new String[FILE_FIELD_NUM];
    static String[] verbsArr = new String[FILE_FIELD_NUM];
    static String[] nounsArr = new String[FILE_FIELD_NUM];

    /**
     * Creates new form MadLibs
     */
    public MadLibs() {
        initComponents();
        
        this.setTitle("Mad Libs");

        //try and load in the data files
        try {
            
            File sentences = new File("src\\guiexercise1\\sentences.txt");
            Scanner scanner1 = new Scanner(sentences);
            
            File verbs = new File("src\\guiexercise1\\verbs.txt");
            Scanner scanner2 = new Scanner(verbs);
            
            File nouns = new File("src\\guiexercise1\\nouns.txt");
            Scanner scanner3 = new Scanner(nouns);
            
            //read the files into arrays
            for (int i = 0; i < FILE_FIELD_NUM; i++) {
                sentencesArr[i] = scanner1.nextLine();
                verbsArr[i] = scanner2.nextLine();
                nounsArr[i] = scanner3.nextLine();
            }
            
        } catch (FileNotFoundException e) {
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        newStrBtn = new javax.swing.JButton();
        libLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 255, 200));
        jPanel1.setForeground(new java.awt.Color(20, 255, 20));

        jPanel2.setBackground(new java.awt.Color(24, 240, 24));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setToolTipText("");

        newStrBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        newStrBtn.setText("Mad Lib!");
        newStrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStrBtnActionPerformed(evt);
            }
        });

        libLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        libLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libLbl.setText("Mad Lib");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(libLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newStrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(libLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(newStrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStrBtnActionPerformed
        // TODO add your handling code here:
        //Pick a random sentence
        randInt = (int) (Math.random() * 10);
        madLib = sentencesArr[randInt];
        
        //find were the verb goes
        verbPos = madLib.indexOf("%");
        
        //get a new verb index
        randInt = (int) (Math.random() * 10);
        
        //inject the verb
        madLib = madLib.substring(0, verbPos) + verbsArr[randInt] +  madLib.substring(verbPos + 1);
        
        //find were the noun goes
        nounPos = madLib.indexOf("#");
        
        //get a new noun index
        randInt = (int) (Math.random() * 10);
        
        //inject the noun
        madLib = madLib.substring(0, nounPos) + nounsArr[randInt] +  madLib.substring(nounPos + 1);
        
        //check if there needs to be come recapitaization
        if(verbPos == 0 || nounPos == 0) {
            madLib = (char)(madLib.charAt(0) - 32) + madLib.substring(1);
        }
        
        //set the new madlib
        libLbl.setText(madLib);
        

    }//GEN-LAST:event_newStrBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MadLibs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MadLibs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MadLibs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MadLibs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MadLibs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel libLbl;
    private javax.swing.JButton newStrBtn;
    // End of variables declaration//GEN-END:variables
}
